In [20]:
import numpy as np
#from math import dist
from math import sqrt
import pandas as pd


In [4]:
p = [[0,11], [-7,1], [-5,-3]]

p = np.array(p)
print(type(p))

a = np.array(p[0:,0:1])
b = np.array(p[0:,1:2])

print(p)
print(f"\n")
#print(a)

#a.append(p[0][0])
#a.append(p[1][0])
#a.append(p[2][0])
#b.append(p[0][1])
#b.append(p[1][1])
#b.append(p[2][1])  

#a = np.array(a)
#b = np.array(b)

#def distancia_euclidiana_3d(a, b):
#    distancia =sqrt(sum([ (a-b) ** 2 for a,b in zip(a, b)] ))
#    return distancia

print (f' a = \n {a} \n b = \n {b}')
#resultado = distancia_euclidiana_3d(a,b)
#print(resultado)

#dit = np.sqrt(np.sum(np.square(a - b)))
#print(dit)
dist =np.linalg.norm(a-b)
print(dist)

<class 'numpy.ndarray'>
[[ 0 11]
 [-7  1]
 [-5 -3]]


 a = 
 [[ 0]
 [-7]
 [-5]] 
 b = 
 [[11]
 [ 1]
 [-3]]
13.74772708486752


In [5]:
p = [[0,11], [-7,1], [-5,-3]] 
p = np.array(p)
c = p.copy() # se copia el array a otra variable, sino se hace esto, se modifica el array original
c = np.array(c)

a = np.array(c[0:,0:1])
b = np.array(c[0:,1:2])
a = np.squeeze(a) # quita la dimension de una matriz
b = np.squeeze(b) # arreta la dimension de una matriz
print(c)
print(f"\n")

print (f'a: {a}  b: {b}')

dist =np.linalg.norm(a-b)
print(dist)

[[ 0 11]
 [-7  1]
 [-5 -3]]


a: [ 0 -7 -5]  b: [11  1 -3]
13.74772708486752


In [6]:
arr = np.linspace(1,10,10, dtype= 'int8')
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
lvariable = arr > 5
lvariable

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [8]:
arr[lvariable]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [9]:
arr[(arr > 5) & (arr<9)] #akt 38 &

array([6, 7, 8], dtype=int8)

In [10]:
array_a = ('abcdfgabccba')
letras = ('abc')
letras_1 = ('cba')
contador = 0

lista = array_a.replace(letras, "1") #reemplaza el conjunto de letras abc por 1
print(lista)
lista = lista.replace(letras_1, "1") #reemplaza el conjunto de letras cba por 1
print(lista)
count = lista.count('1') #cuenta las veces que aparece 1
print(count)# imprime la suma de las veces que aparece 1

       

1dfg1cba
1dfg11
3


In [15]:
ay = np.array([[1,2,3,4],[4,5,6],[7,8,9]]).ndim

print(ay)

2


In [25]:
z = np.linspace(0,10,100)
print(z)

[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818  8

[ 3  3  5  6  6 10 13]


AttributeError: module 'pandas' has no attribute 'del_duplicates'